# Generated by Django 4.2.4 on 2023-08-18 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='cow',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.food'),
        ),
        migrations.AddField(
            model_name='cow',
            name='is_male',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='cow',
            name='logs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.report'),
        ),
        migrations.AddField(
            model_name='cow',
            name='state',
            field=models.CharField(blank=True, choices=[('Dry', 'Dry'), ('Marigeable', 'Marigeable'), ('Prgnent', 'Prgnent'), ('Milk', 'Milk')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='howmuch',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='kgto4ekarah',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cow',
            name='age',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='cow',
            name='name',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='milk',
            name='how_much',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='shekara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.food')),
            ],
        ),
    ]
